; Auto-generated. Do not edit!


(cl:in-package navigation-msg)


;//! \htmlinclude LocalisationGoal.msg.html

(cl:defclass <LocalisationGoal> (roslisp-msg-protocol:ros-message)
  ((target
    :reader target
    :initarg :target
    :type cl:integer
    :initform 0))
)

(cl:defclass LocalisationGoal (<LocalisationGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LocalisationGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LocalisationGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name navigation-msg:<LocalisationGoal> is deprecated: use navigation-msg:LocalisationGoal instead.")))

(cl:ensure-generic-function 'target-val :lambda-list '(m))
(cl:defmethod target-val ((m <LocalisationGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader navigation-msg:target-val is deprecated.  Use navigation-msg:target instead.")
  (target m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LocalisationGoal>) ostream)
  "Serializes a message object of type '<LocalisationGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'target)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'target)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'target)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'target)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LocalisationGoal>) istream)
  "Deserializes a message object of type '<LocalisationGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'target)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'target)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'target)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'target)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LocalisationGoal>)))
  "Returns string type for a message object of type '<LocalisationGoal>"
  "navigation/LocalisationGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LocalisationGoal)))
  "Returns string type for a message object of type 'LocalisationGoal"
  "navigation/LocalisationGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LocalisationGoal>)))
  "Returns md5sum for a message object of type '<LocalisationGoal>"
  "e8f971e83c003dca3d6eef9786213230")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LocalisationGoal)))
  "Returns md5sum for a message object of type 'LocalisationGoal"
  "e8f971e83c003dca3d6eef9786213230")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LocalisationGoal>)))
  "Returns full string definition for message of type '<LocalisationGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 target  # indique la destination~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LocalisationGoal)))
  "Returns full string definition for message of type 'LocalisationGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 target  # indique la destination~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LocalisationGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LocalisationGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LocalisationGoal
    (cl:cons ':target (target msg))
))
