; Auto-generated. Do not edit!


(cl:in-package navigation-msg)


;//! \htmlinclude LocalisationFeedback.msg.html

(cl:defclass <LocalisationFeedback> (roslisp-msg-protocol:ros-message)
  ((current_pose
    :reader current_pose
    :initarg :current_pose
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass LocalisationFeedback (<LocalisationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LocalisationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LocalisationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name navigation-msg:<LocalisationFeedback> is deprecated: use navigation-msg:LocalisationFeedback instead.")))

(cl:ensure-generic-function 'current_pose-val :lambda-list '(m))
(cl:defmethod current_pose-val ((m <LocalisationFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader navigation-msg:current_pose-val is deprecated.  Use navigation-msg:current_pose instead.")
  (current_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LocalisationFeedback>) ostream)
  "Serializes a message object of type '<LocalisationFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'current_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LocalisationFeedback>) istream)
  "Deserializes a message object of type '<LocalisationFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'current_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LocalisationFeedback>)))
  "Returns string type for a message object of type '<LocalisationFeedback>"
  "navigation/LocalisationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LocalisationFeedback)))
  "Returns string type for a message object of type 'LocalisationFeedback"
  "navigation/LocalisationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LocalisationFeedback>)))
  "Returns md5sum for a message object of type '<LocalisationFeedback>"
  "dd7058fae6e1bf2400513fe092a44c92")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LocalisationFeedback)))
  "Returns md5sum for a message object of type 'LocalisationFeedback"
  "dd7058fae6e1bf2400513fe092a44c92")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LocalisationFeedback>)))
  "Returns full string definition for message of type '<LocalisationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%geometry_msgs/PoseStamped current_pose~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LocalisationFeedback)))
  "Returns full string definition for message of type 'LocalisationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%geometry_msgs/PoseStamped current_pose~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LocalisationFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'current_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LocalisationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LocalisationFeedback
    (cl:cons ':current_pose (current_pose msg))
))
