# Vel Controllers ---------------------------------------
joint1_vel_controller:
  type: effort_controllers/JointEffortController
  joint: cylinder1_joint
  pid: {p: 2000.0, i: 100, d: 500.0}
joint2_vel_controller:
  type: effort_controllers/JointEffortController
  joint: cylinder2_joint
  pid: {p: 50000.0, i: 100, d: 2000.0}