// Generated by gencpp from file navigation/LocalisationResult.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_LOCALISATIONRESULT_H
#define NAVIGATION_MESSAGE_LOCALISATIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct LocalisationResult_
{
  typedef LocalisationResult_<ContainerAllocator> Type;

  LocalisationResult_()
    : result_code(0)  {
    }
  LocalisationResult_(const ContainerAllocator& _alloc)
    : result_code(0)  {
  (void)_alloc;
    }



   typedef uint32_t _result_code_type;
  _result_code_type result_code;





  typedef boost::shared_ptr< ::navigation::LocalisationResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::LocalisationResult_<ContainerAllocator> const> ConstPtr;

}; // struct LocalisationResult_

typedef ::navigation::LocalisationResult_<std::allocator<void> > LocalisationResult;

typedef boost::shared_ptr< ::navigation::LocalisationResult > LocalisationResultPtr;
typedef boost::shared_ptr< ::navigation::LocalisationResult const> LocalisationResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::LocalisationResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::LocalisationResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::LocalisationResult_<ContainerAllocator1> & lhs, const ::navigation::LocalisationResult_<ContainerAllocator2> & rhs)
{
  return lhs.result_code == rhs.result_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::LocalisationResult_<ContainerAllocator1> & lhs, const ::navigation::LocalisationResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::navigation::LocalisationResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::LocalisationResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::LocalisationResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::LocalisationResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::LocalisationResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::LocalisationResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::LocalisationResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ef5c02243cd2c6c3b25e8d094bd9470";
  }

  static const char* value(const ::navigation::LocalisationResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ef5c02243cd2c6cULL;
  static const uint64_t static_value2 = 0x3b25e8d094bd9470ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::LocalisationResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/LocalisationResult";
  }

  static const char* value(const ::navigation::LocalisationResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::LocalisationResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"uint32 result_code #un numero pour défenir le resultat de la navigation\n"
;
  }

  static const char* value(const ::navigation::LocalisationResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::LocalisationResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalisationResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::LocalisationResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::LocalisationResult_<ContainerAllocator>& v)
  {
    s << indent << "result_code: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.result_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_LOCALISATIONRESULT_H
