// Generated by gencpp from file navigation/LocalisationGoal.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_LOCALISATIONGOAL_H
#define NAVIGATION_MESSAGE_LOCALISATIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct LocalisationGoal_
{
  typedef LocalisationGoal_<ContainerAllocator> Type;

  LocalisationGoal_()
    : target(0)  {
    }
  LocalisationGoal_(const ContainerAllocator& _alloc)
    : target(0)  {
  (void)_alloc;
    }



   typedef uint32_t _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::navigation::LocalisationGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::LocalisationGoal_<ContainerAllocator> const> ConstPtr;

}; // struct LocalisationGoal_

typedef ::navigation::LocalisationGoal_<std::allocator<void> > LocalisationGoal;

typedef boost::shared_ptr< ::navigation::LocalisationGoal > LocalisationGoalPtr;
typedef boost::shared_ptr< ::navigation::LocalisationGoal const> LocalisationGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::LocalisationGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::LocalisationGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'navigation': ['/home/pal/intership_project/devel/.private/navigation/share/navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation::LocalisationGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::LocalisationGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::LocalisationGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::LocalisationGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::LocalisationGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::LocalisationGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::LocalisationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8f971e83c003dca3d6eef9786213230";
  }

  static const char* value(const ::navigation::LocalisationGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8f971e83c003dcaULL;
  static const uint64_t static_value2 = 0x3d6eef9786213230ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::LocalisationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/LocalisationGoal";
  }

  static const char* value(const ::navigation::LocalisationGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::LocalisationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"uint32 target  # indique la destination\n"
;
  }

  static const char* value(const ::navigation::LocalisationGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::LocalisationGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalisationGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::LocalisationGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::LocalisationGoal_<ContainerAllocator>& v)
  {
    s << indent << "target: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_LOCALISATIONGOAL_H
