// Generated by gencpp from file navigation/move_base.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_MOVE_BASE_H
#define NAVIGATION_MESSAGE_MOVE_BASE_H

#include <ros/service_traits.h>


#include <navigation/move_baseRequest.h>
#include <navigation/move_baseResponse.h>


namespace navigation
{

struct move_base
{

typedef move_baseRequest Request;
typedef move_baseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move_base
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::move_base > {
  static const char* value()
  {
    return "f4bf476788e86695cf4dce503ea03010";
  }

  static const char* value(const ::navigation::move_base&) { return value(); }
};

template<>
struct DataType< ::navigation::move_base > {
  static const char* value()
  {
    return "navigation/move_base";
  }

  static const char* value(const ::navigation::move_base&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::move_baseRequest> should match 
// service_traits::MD5Sum< ::navigation::move_base > 
template<>
struct MD5Sum< ::navigation::move_baseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::move_base >::value();
  }
  static const char* value(const ::navigation::move_baseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::move_baseRequest> should match 
// service_traits::DataType< ::navigation::move_base > 
template<>
struct DataType< ::navigation::move_baseRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::move_base >::value();
  }
  static const char* value(const ::navigation::move_baseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::move_baseResponse> should match 
// service_traits::MD5Sum< ::navigation::move_base > 
template<>
struct MD5Sum< ::navigation::move_baseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::move_base >::value();
  }
  static const char* value(const ::navigation::move_baseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::move_baseResponse> should match 
// service_traits::DataType< ::navigation::move_base > 
template<>
struct DataType< ::navigation::move_baseResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::move_base >::value();
  }
  static const char* value(const ::navigation::move_baseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_MOVE_BASE_H
